### ISSUE TITLE
Executing cuts

### ISSUE THREAD

**Issue by Alexwilmac** [opendreambox/enigma2-plugin-moviecut#1]
Hello, without any doubts Moviecut is my favourite plugin. There is a little difference between BH and OBH (since 0.6 till current 4.1) in this:
-in BH, after you have set the cut points, going backwards you have immediately the command to execute cuts;
-in OBH, instead, you must exit the menu of moviecut, select again the movie and then you can give the command to execute the cuts.
Why's this difference?

And finally: it'd be fantastic if the real cut points, set by moviecut when you choose a marked point, were b-frames, so that the cut would be perfect. Is it possible to implement this feature in the future releases?
Many compliments for the plugins!

**Comment by dhwz** [comment]
BH? OBH?

**Comment by Alexwilmac** [comment]
BH=BlackHole (currently ver. 3.0.5)
OBH= OpenBlackHole  (currently ver. 4.1.013)
images for Enigma2-based receivers VU+

**Comment by dhwz** [comment]
Then you misunderstood something, check the name of this GIT again: **opendreambox**
You won't get support for any other hardware.
